name: directus-cms-template
services:
  database:
    image: postgis/postgis:13-master
    ports:
      - "5432:5432"
    platform: linux/amd64
    volumes:
      - ./database/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: directus

  cache:
    image: redis:6
    ports:
      - "6379:6379"

